//
// Created by root on 12/30/18.
//

#ifndef UDPFLOW_ERRORS_H
#define UDPFLOW_ERRORS_H
typedef enum udpflow_res_e{
    UDPFLOW_UNINITIALIZED = -1,
    UDPFLOW_SUCCESS = 0,
    UDPFLOW_FAILURE = 1,


    UDPFLOW_PCAP_READ_ERROR = 1000,


    UDPFLOW_METADATA_BAD_PARMATERS = 2000,
    UDPFLOW_METADATA_INIT_MALLOC_FAILURE_ALLOCATE_OBJECT = 2001,
    UDPFLOW_DATA_BAD_PARMATERS = 3000,
    UDPFLOW_DATA_INIT_MALLOC_FAILURE_ALLOCATE_OBJECT = 3001,
    UDPFLOW_DATA_INIT_MALLOC_FAILURE_ALLOCATE_BUFFER = 3002,
    UDPFLOW_PARSE_FIRST_PACKET_NO_ETH=4000,
    UDPFLOW_PARSE_FIRST_PACKET_NO_IP=4001,
    UDPFLOW_PARSE_FIRST_PACKET_NO_UDP=4002,
    UDPFLOW_OUTPUT_BAD_PARAMETERS=5000,
    UDPFLOW_OUTPUT_READFILE_CANNOT_OPEN_FILE=5001,
    UDPFLOW_OUTPUT_CREATEFILE_BAD_PARAMETERS=5010,
    UDDFLOW_OUTPUT_CREATEFILE_COULDENT_CREATE_FILE=5011,
    UDPFLOW_OUTPUT_JSON_OPENING_WRITE_BAD_PARAMETERS=5021,
    UDPFLOW_OUTPUT_JSON_CLOSING_WRITE_BAD_PARAMETERS=5022,
    UDPFLOW_ORCH_BAD_PARAMETER=6000,
    UDPFLOW_ORCH_COULDENT_CREATE_FILE=6001,
    UDPFLOW_ORCH_COULDENT_WRITE_OPENNING=6002,
    UDPFLOW_ORCH_COULDENT_PARSE_INPUT_PCAP=6003,
    UDPFLOW_ORCH_COULDENT_WRITE_ENDING=6004
} udpflow_res_t;


#endif //UDPFLOW_ERRORS_H
