# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cytos/Code/udpFlowgit/UdpFlow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cytos/Code/udpFlowgit/UdpFlow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cytos/Code/udpFlowgit/UdpFlow/CMakeFiles /home/cytos/Code/udpFlowgit/UdpFlow/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cytos/Code/udpFlowgit/UdpFlow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UdpFlow

# Build rule for target.
UdpFlow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UdpFlow
.PHONY : UdpFlow

# fast build rule for target.
UdpFlow/fast:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/build
.PHONY : UdpFlow/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/main.c.s
.PHONY : main.c.s

orchestrator.o: orchestrator.c.o

.PHONY : orchestrator.o

# target to build an object file
orchestrator.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/orchestrator.c.o
.PHONY : orchestrator.c.o

orchestrator.i: orchestrator.c.i

.PHONY : orchestrator.i

# target to preprocess a source file
orchestrator.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/orchestrator.c.i
.PHONY : orchestrator.c.i

orchestrator.s: orchestrator.c.s

.PHONY : orchestrator.s

# target to generate assembly for a file
orchestrator.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/orchestrator.c.s
.PHONY : orchestrator.c.s

pcap_processing/data_types/session_data.o: pcap_processing/data_types/session_data.c.o

.PHONY : pcap_processing/data_types/session_data.o

# target to build an object file
pcap_processing/data_types/session_data.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/data_types/session_data.c.o
.PHONY : pcap_processing/data_types/session_data.c.o

pcap_processing/data_types/session_data.i: pcap_processing/data_types/session_data.c.i

.PHONY : pcap_processing/data_types/session_data.i

# target to preprocess a source file
pcap_processing/data_types/session_data.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/data_types/session_data.c.i
.PHONY : pcap_processing/data_types/session_data.c.i

pcap_processing/data_types/session_data.s: pcap_processing/data_types/session_data.c.s

.PHONY : pcap_processing/data_types/session_data.s

# target to generate assembly for a file
pcap_processing/data_types/session_data.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/data_types/session_data.c.s
.PHONY : pcap_processing/data_types/session_data.c.s

pcap_processing/data_types/session_metadata.o: pcap_processing/data_types/session_metadata.c.o

.PHONY : pcap_processing/data_types/session_metadata.o

# target to build an object file
pcap_processing/data_types/session_metadata.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/data_types/session_metadata.c.o
.PHONY : pcap_processing/data_types/session_metadata.c.o

pcap_processing/data_types/session_metadata.i: pcap_processing/data_types/session_metadata.c.i

.PHONY : pcap_processing/data_types/session_metadata.i

# target to preprocess a source file
pcap_processing/data_types/session_metadata.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/data_types/session_metadata.c.i
.PHONY : pcap_processing/data_types/session_metadata.c.i

pcap_processing/data_types/session_metadata.s: pcap_processing/data_types/session_metadata.c.s

.PHONY : pcap_processing/data_types/session_metadata.s

# target to generate assembly for a file
pcap_processing/data_types/session_metadata.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/data_types/session_metadata.c.s
.PHONY : pcap_processing/data_types/session_metadata.c.s

pcap_processing/output_methods/file_operations.o: pcap_processing/output_methods/file_operations.c.o

.PHONY : pcap_processing/output_methods/file_operations.o

# target to build an object file
pcap_processing/output_methods/file_operations.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/output_methods/file_operations.c.o
.PHONY : pcap_processing/output_methods/file_operations.c.o

pcap_processing/output_methods/file_operations.i: pcap_processing/output_methods/file_operations.c.i

.PHONY : pcap_processing/output_methods/file_operations.i

# target to preprocess a source file
pcap_processing/output_methods/file_operations.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/output_methods/file_operations.c.i
.PHONY : pcap_processing/output_methods/file_operations.c.i

pcap_processing/output_methods/file_operations.s: pcap_processing/output_methods/file_operations.c.s

.PHONY : pcap_processing/output_methods/file_operations.s

# target to generate assembly for a file
pcap_processing/output_methods/file_operations.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/output_methods/file_operations.c.s
.PHONY : pcap_processing/output_methods/file_operations.c.s

pcap_processing/output_methods/json_output.o: pcap_processing/output_methods/json_output.c.o

.PHONY : pcap_processing/output_methods/json_output.o

# target to build an object file
pcap_processing/output_methods/json_output.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/output_methods/json_output.c.o
.PHONY : pcap_processing/output_methods/json_output.c.o

pcap_processing/output_methods/json_output.i: pcap_processing/output_methods/json_output.c.i

.PHONY : pcap_processing/output_methods/json_output.i

# target to preprocess a source file
pcap_processing/output_methods/json_output.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/output_methods/json_output.c.i
.PHONY : pcap_processing/output_methods/json_output.c.i

pcap_processing/output_methods/json_output.s: pcap_processing/output_methods/json_output.c.s

.PHONY : pcap_processing/output_methods/json_output.s

# target to generate assembly for a file
pcap_processing/output_methods/json_output.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/output_methods/json_output.c.s
.PHONY : pcap_processing/output_methods/json_output.c.s

pcap_processing/wrappers/netinet_wrapper.o: pcap_processing/wrappers/netinet_wrapper.c.o

.PHONY : pcap_processing/wrappers/netinet_wrapper.o

# target to build an object file
pcap_processing/wrappers/netinet_wrapper.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/wrappers/netinet_wrapper.c.o
.PHONY : pcap_processing/wrappers/netinet_wrapper.c.o

pcap_processing/wrappers/netinet_wrapper.i: pcap_processing/wrappers/netinet_wrapper.c.i

.PHONY : pcap_processing/wrappers/netinet_wrapper.i

# target to preprocess a source file
pcap_processing/wrappers/netinet_wrapper.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/wrappers/netinet_wrapper.c.i
.PHONY : pcap_processing/wrappers/netinet_wrapper.c.i

pcap_processing/wrappers/netinet_wrapper.s: pcap_processing/wrappers/netinet_wrapper.c.s

.PHONY : pcap_processing/wrappers/netinet_wrapper.s

# target to generate assembly for a file
pcap_processing/wrappers/netinet_wrapper.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/wrappers/netinet_wrapper.c.s
.PHONY : pcap_processing/wrappers/netinet_wrapper.c.s

pcap_processing/wrappers/pcap_wrapper.o: pcap_processing/wrappers/pcap_wrapper.c.o

.PHONY : pcap_processing/wrappers/pcap_wrapper.o

# target to build an object file
pcap_processing/wrappers/pcap_wrapper.c.o:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/wrappers/pcap_wrapper.c.o
.PHONY : pcap_processing/wrappers/pcap_wrapper.c.o

pcap_processing/wrappers/pcap_wrapper.i: pcap_processing/wrappers/pcap_wrapper.c.i

.PHONY : pcap_processing/wrappers/pcap_wrapper.i

# target to preprocess a source file
pcap_processing/wrappers/pcap_wrapper.c.i:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/wrappers/pcap_wrapper.c.i
.PHONY : pcap_processing/wrappers/pcap_wrapper.c.i

pcap_processing/wrappers/pcap_wrapper.s: pcap_processing/wrappers/pcap_wrapper.c.s

.PHONY : pcap_processing/wrappers/pcap_wrapper.s

# target to generate assembly for a file
pcap_processing/wrappers/pcap_wrapper.c.s:
	$(MAKE) -f CMakeFiles/UdpFlow.dir/build.make CMakeFiles/UdpFlow.dir/pcap_processing/wrappers/pcap_wrapper.c.s
.PHONY : pcap_processing/wrappers/pcap_wrapper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... UdpFlow"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... orchestrator.o"
	@echo "... orchestrator.i"
	@echo "... orchestrator.s"
	@echo "... pcap_processing/data_types/session_data.o"
	@echo "... pcap_processing/data_types/session_data.i"
	@echo "... pcap_processing/data_types/session_data.s"
	@echo "... pcap_processing/data_types/session_metadata.o"
	@echo "... pcap_processing/data_types/session_metadata.i"
	@echo "... pcap_processing/data_types/session_metadata.s"
	@echo "... pcap_processing/output_methods/file_operations.o"
	@echo "... pcap_processing/output_methods/file_operations.i"
	@echo "... pcap_processing/output_methods/file_operations.s"
	@echo "... pcap_processing/output_methods/json_output.o"
	@echo "... pcap_processing/output_methods/json_output.i"
	@echo "... pcap_processing/output_methods/json_output.s"
	@echo "... pcap_processing/wrappers/netinet_wrapper.o"
	@echo "... pcap_processing/wrappers/netinet_wrapper.i"
	@echo "... pcap_processing/wrappers/netinet_wrapper.s"
	@echo "... pcap_processing/wrappers/pcap_wrapper.o"
	@echo "... pcap_processing/wrappers/pcap_wrapper.i"
	@echo "... pcap_processing/wrappers/pcap_wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

